### ISSUE TITLE
act.base.ResponseError

### ISSUE THREAD

**Issue by nakagit** [mnemonic-no/act-bootstrap#17]
Hi 

When I executed following command, error occurred.
`./scripts/act-bootstrap.sh 1 http://localhost:8888`
![190322-0004](https://user-images.githubusercontent.com/10558255/54779785-5e56ea00-4c5b-11e9-9290-bebf332ff250.png)

Did I do something wrong or missing?

Kind regards,
Yuki

**Comment by frbor** [comment]
Hi,

it looks like there are some changes that has not been implemented after we have updated the data model. However, this is only for one of the bootstrap workers (misp-threat-actors.py) and you will get the most of the same data with only adding data from Mitre Attack, so I sould advise to comment out bootstrap/misp-threat-actor.py from scripts/act-bootstrap.sh and you should be able to get this working without any errors.

best regards,

   Fredrik

**Comment by nakagit** [comment]
Hi

Big thanks for your help. :)

But, I'm afraid my issue didn't fixed.

What I did were followings:
1) Commented out bootstrap/misp-threat-actor.py from scripts/act-bootstrap.sh.
2) Executed '`./scripts/act-bootstrap.sh 1 http://localhost:8888`'.
![190324-0001](https://user-images.githubusercontent.com/10558255/54874213-f1457f00-4e29-11e9-8d57-6f8a75e0f318.png)


I'm stuck here and confused about ACT-modules out there. If you know that 
the correct order of installation.
1 - ACT-platform
    https://github.com/mnemonic-no/act-platform
2 - ACT-bootstrap
    https://github.com/mnemonic-no/act-bootstrap
3 - ACT-api-python
    https://github.com/mnemonic-no/act-api-python
4 - ACT-workers
    https://github.com/mnemonic-no/act-workers
5 - ACT Frontend
    https://github.com/mnemonic-no/act-frontend

Question(1): Above installation order is correct?
Question(2): Can we get organized installation documents?


Many thanks,
Yuki

**Comment by frbor** [comment]
Hi,

unfortunately, your problems with the act-bootstrap was due to a PR that was not merged (https://github.com/mnemonic-no/act-bootstrap/pull/16/). We have now merged this, and you should be able to update the act-bootstrap repo and rerun the command. The order for your installation should be more ore less correct, although you should install act-api-python before act-bootstrap (but you have most likeley done so, if not you would have gotten other errors during bootstrap).

We are aware of the missing documentation, and it is on the road map to create installation documentation. However, for the time being we are happy that you are patient and are willing to give feedback and test the platform.

best regards,

   Fredrik

**Comment by frbor** [comment]
Hi, I have not heard from you after my previous update, so I justed wanted to let you know that we will close this issue unless you have anything more to add.

best regards,

   Fredrik

**Comment by nakagit** [comment]
I'm sorry I've been busy and no time to play ACT.
BTW, which distribution would be the best for ACT?

Many thanks,
Yuki

**Comment by frbor** [comment]
Hi,

we are primarily using CentOS 7.x, but have also successfully installed the platform on debian. The deployment guide which hopefully should be finished within a couple of weeks will include detailed instructions on how to configure all parts on CentOS 7.x.

best regards,

   Fredrik

**Comment by frbor** [comment]
The installation guide is now published [here](https://github.com/mnemonic-no/act).

We will close this incident, but please let us know if you have any other questions.
